# SCRAPING AUTOMART CAR PRICES DATA

Source: https://www.brecorder.com/news/40111873

In [1]:
!pip install requests

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")

Requirement already satisfied: requests in c:\users\hp\anaconda3\lib\site-packages (2.19.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\hp\anaconda3\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2018.8.24)
Requirement already satisfied: idna<2.8,>=2.5 in c:\users\hp\anaconda3\lib\site-packages (from requests) (2.7)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in c:\users\hp\anaconda3\lib\site-packages (from requests) (1.23)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 21.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [2]:
!pip install bs4

Requirement already satisfied: bs4 in c:\users\hp\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\anaconda3\lib\site-packages (from bs4) (4.6.3)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 21.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [3]:
!pip install html5lib

Requirement already satisfied: html5lib in c:\users\hp\anaconda3\lib\site-packages (1.0.1)
Requirement already satisfied: six>=1.9 in c:\users\hp\anaconda3\lib\site-packages (from html5lib) (1.14.0)
Requirement already satisfied: webencodings in c:\users\hp\anaconda3\lib\site-packages (from html5lib) (0.5.1)

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
You are using pip version 10.0.1, however version 21.2.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [4]:
import requests
from bs4 import BeautifulSoup

In [5]:
url = "https://www.brecorder.com/news/40111873"

In [6]:
r = requests.get(url)
htmlContent = r.content
# print(htmlContent)

In [7]:
soup = BeautifulSoup(htmlContent, "html.parser")
# print(soup.prettify)

In [8]:
title = soup.title

In [9]:
paras = soup.find_all("p")
# print(paras)

In [10]:
anchors = soup.find_all("a")
# print(anchors)

In [11]:
print(soup.find("p"))

<p><strong>KARACHI: The prices of different makes and models of cars prevailing in Karachi in the week ended Saturday (August 7, 2021).</strong></p>

In [12]:
print(soup.find("strong"))

<strong>KARACHI: The prices of different makes and models of cars prevailing in Karachi in the week ended Saturday (August 7, 2021).</strong>

In [13]:
print(soup.find("p").get_text())

KARACHI: The prices of different makes and models of cars prevailing in Karachi in the week ended Saturday (August 7, 2021).

In [14]:
main_code = soup.find("code").get_text()
print(main_code)

===========================================================================
                                            Prices
Product Description                                    Fully
                                          Standard      A/C          Loaded
                                             Model     Model          Model
===========================================================================
SUZUKI
---------------------------------------------------------------------------
Alto 660cc
---------------------------------------------------------------------------
Alto VX                                 1,113,000/-                       -
Alto VXR                                1,335,000/-                       -
Alto VXL                                1,521,000/-                       -
---------------------------------------------------------------------------
WAGONR-1000cc
---------------------------------------------------------------------------
WagonR VXR                              1,530,000/-                       -
WagonR VXL                              1,610,000/-                       -
WagonR AGS                              1,760,000/-                       -
---------------------------------------------------------------------------
CULTUS-1000cc
---------------------------------------------------------------------------
Cultus VXR                              1,655,000/-                       -
Cultus VXL                              1,830,000/-                       -
Cultus Auto Gear Shift                  1,975,000/-                       -
---------------------------------------------------------------------------
SWIFT-1300cc
---------------------------------------------------------------------------
Swift DLX 1.3 Navigation                1,972,000/-                       -
Swift DLX Automatic 1.3 Navigation      2,148,000/-                       -
---------------------------------------------------------------------------
JIMNY-1600cc
---------------------------------------------------------------------------
Jimny GA MT                             4,490,000/-                       -
---------------------------------------------------------------------------
VITARA-1600cc
---------------------------------------------------------------------------
Vitara GLX 1.6                          6,500,000/-                       -
---------------------------------------------------------------------------
BOLAN-800cc
---------------------------------------------------------------------------
VX Euro II                              1,049,000/-                       -
Cargo Van Euro II                       1,075,000/-                       -
---------------------------------------------------------------------------
RAVI Pickup-800cc
---------------------------------------------------------------------------
Ravi Euro II                            1,034,000/-                       -
---------------------------------------------------------------------------
TOYOTA
---------------------------------------------------------------------------
Toyota Yaris ATIV CVT 1.3               2,669,000/-                       -
Toyota Yaris ATIV MT 1.3                2,519,000/-                       -
Toyota Yaris ATIV X CVT 1.5             2,899,000/-                       -
Toyota Yaris ATIV X MT 1.5              2,719,000/-                       -
Toyota Yaris GLI CVT 1.3                2,589,000/-                       -
Toyota Yaris GLI MT 1.3                 2,409,000/-                       -
Corolla Altis Manual 1.6                3,109,000/-                       -
Corolla Altis Automatic 1.6             3,249,000/-                       -
Corolla Altis CVT-i 1.8                 3,579,000/-                       -
Corolla Altis Grande 1.8 (Beige Inter   3,869,000/-                       -
Corolla Altis Grande CVT-i 1.8 (Black   3,889,000/-                       -
Hilux 4x2 S/C Deckless                  3,569,000/-                       -
Hilux 4x2 S/C Standard                  3,819,000/-                       -
Hilux 4x4 S/C Standard 2.8              5,169,000/-                       -
Hilux E 2.8                             5,859,000/-                       -
Hilux REVO G 2.8                        6,429,000/-                       -
Hilux REVO G Automatic 2.8              6,779,000/-                       -
Hilux REVO V Automatic 2.8              7,379,000/-                       -
Fortuner 2.7 G                          7,649,000/-                       -
Fortuner 2.7 VVTi                       8,899,000/-                       -
Fortuner 2.8 Sigma 4                    9,269,000/-                       -
---------------------------------------------------------------------------
HONDA
---------------------------------------------------------------------------
Civic 1.5 Rs Turbo                      4,564,000/-                       -
Civic 1.8 i-VTEC CVT                    3,614,000/-                       -
Civic Oriel 1.8 i-VTEC CVT              3,864,000/-                       -
Accord 1.5L VTEC?Turbo                 11,999,000/-                       -
BR-V i-VTEC S                           3,374,000/-                       -
CR-V 2.0 CVT                           10,700,000/-                       -
1.3L & 1.5L (City, Aspire, BR-V, Civic Filer 50,000 OR 1.8L (Civic) 75,000.
===========================================================================

In [16]:
import pandas as pd
from io import StringIO
import re
df = pd.read_csv(StringIO(re.sub(r'[=-]','',main_code)), sep='\s{2,}', engine="python")
df

                                                                Prices
Product Description                                Fully
Standard                                           A/C          Loaded
Model                                              Model         Model
SUZUKI                                             NaN            None
Alto 660cc                                         NaN            None
Alto VX                                            1,113,000/     None
Alto VXR                                           1,335,000/     None
Alto VXL                                           1,521,000/     None
WAGONR1000cc                                       NaN            None
WagonR VXR                                         1,530,000/     None
WagonR VXL                                         1,610,000/     None
WagonR AGS                                         1,760,000/     None
CULTUS1000cc                                       NaN            None
Cultus VXR                                         1,655,000/     None
Cultus VXL                                         1,830,000/     None
Cultus Auto Gear Shift                             1,975,000/     None
SWIFT1300cc                                        NaN            None
Swift DLX 1.3 Navigation                           1,972,000/     None
Swift DLX Automatic 1.3 Navigation                 2,148,000/     None
JIMNY1600cc                                        NaN            None
Jimny GA MT                                        4,490,000/     None
VITARA1600cc                                       NaN            None
Vitara GLX 1.6                                     6,500,000/     None
BOLAN800cc                                         NaN            None
VX Euro II                                         1,049,000/     None
Cargo Van Euro II                                  1,075,000/     None
RAVI Pickup800cc                                   NaN            None
Ravi Euro II                                       1,034,000/     None
TOYOTA                                             NaN            None
Toyota Yaris ATIV CVT 1.3                          2,669,000/     None
Toyota Yaris ATIV MT 1.3                           2,519,000/     None
Toyota Yaris ATIV X CVT 1.5                        2,899,000/     None
Toyota Yaris ATIV X MT 1.5                         2,719,000/     None
Toyota Yaris GLI CVT 1.3                           2,589,000/     None
Toyota Yaris GLI MT 1.3                            2,409,000/     None
Corolla Altis Manual 1.6                           3,109,000/     None
Corolla Altis Automatic 1.6                        3,249,000/     None
Corolla Altis CVTi 1.8                             3,579,000/     None
Corolla Altis Grande 1.8 (Beige Inter              3,869,000/     None
Corolla Altis Grande CVTi 1.8 (Black               3,889,000/     None
Hilux 4x2 S/C Deckless                             3,569,000/     None
Hilux 4x2 S/C Standard                             3,819,000/     None
Hilux 4x4 S/C Standard 2.8                         5,169,000/     None
Hilux E 2.8                                        5,859,000/     None
Hilux REVO G 2.8                                   6,429,000/     None
Hilux REVO G Automatic 2.8                         6,779,000/     None
Hilux REVO V Automatic 2.8                         7,379,000/     None
Fortuner 2.7 G                                     7,649,000/     None
Fortuner 2.7 VVTi                                  8,899,000/     None
Fortuner 2.8 Sigma 4                               9,269,000/     None
HONDA                                              NaN            None
Civic 1.5 Rs Turbo                                 4,564,000/     None
Civic 1.8 iVTEC CVT                                3,614,000/     None
Civic Oriel 1.8 iVTEC CVT                          3,864,000/     None
Accord 1.5L VTEC?Turbo                             11,999,000/    None
BRV iVTEC S                                        3,374,000/     None
CRV 2.0 CVT                                        10,700,000/    None
1.3L & 1.5L (City, Aspire, BRV, Civic Filer 50,... NaN            None

In [17]:
del(df["Prices"])

In [18]:
df

Empty DataFrame
Columns: []
Index: [(Standard, A/C), (Model, Model), (SUZUKI, nan), (Alto 660cc, nan), (Alto VX, 1,113,000/), (Alto VXR, 1,335,000/), (Alto VXL, 1,521,000/), (WAGONR1000cc, nan), (WagonR VXR, 1,530,000/), (WagonR VXL, 1,610,000/), (WagonR AGS, 1,760,000/), (CULTUS1000cc, nan), (Cultus VXR, 1,655,000/), (Cultus VXL, 1,830,000/), (Cultus Auto Gear Shift, 1,975,000/), (SWIFT1300cc, nan), (Swift DLX 1.3 Navigation, 1,972,000/), (Swift DLX Automatic 1.3 Navigation, 2,148,000/), (JIMNY1600cc, nan), (Jimny GA MT, 4,490,000/), (VITARA1600cc, nan), (Vitara GLX 1.6, 6,500,000/), (BOLAN800cc, nan), (VX Euro II, 1,049,000/), (Cargo Van Euro II, 1,075,000/), (RAVI Pickup800cc, nan), (Ravi Euro II, 1,034,000/), (TOYOTA, nan), (Toyota Yaris ATIV CVT 1.3, 2,669,000/), (Toyota Yaris ATIV MT 1.3, 2,519,000/), (Toyota Yaris ATIV X CVT 1.5, 2,899,000/), (Toyota Yaris ATIV X MT 1.5, 2,719,000/), (Toyota Yaris GLI CVT 1.3, 2,589,000/), (Toyota Yaris GLI MT 1.3, 2,409,000/), (Corolla Altis Manual 1.6, 3,109,000/), (Corolla Altis Automatic 1.6, 3,249,000/), (Corolla Altis CVTi 1.8, 3,579,000/), (Corolla Altis Grande 1.8 (Beige Inter, 3,869,000/), (Corolla Altis Grande CVTi 1.8 (Black, 3,889,000/), (Hilux 4x2 S/C Deckless, 3,569,000/), (Hilux 4x2 S/C Standard, 3,819,000/), (Hilux 4x4 S/C Standard 2.8, 5,169,000/), (Hilux E 2.8, 5,859,000/), (Hilux REVO G 2.8, 6,429,000/), (Hilux REVO G Automatic 2.8, 6,779,000/), (Hilux REVO V Automatic 2.8, 7,379,000/), (Fortuner 2.7 G, 7,649,000/), (Fortuner 2.7 VVTi, 8,899,000/), (Fortuner 2.8 Sigma 4, 9,269,000/), (HONDA, nan), (Civic 1.5 Rs Turbo, 4,564,000/), (Civic 1.8 iVTEC CVT, 3,614,000/), (Civic Oriel 1.8 iVTEC CVT, 3,864,000/), (Accord 1.5L VTEC?Turbo, 11,999,000/), (BRV iVTEC S, 3,374,000/), (CRV 2.0 CVT, 10,700,000/), (1.3L & 1.5L (City, Aspire, BRV, Civic Filer 50,000 OR 1.8L (Civic) 75,000., nan)]

In [19]:
df = df.reset_index()

In [20]:
df.dropna(inplace=True)

In [21]:
df["Fully"].dtype

dtype('O')

In [22]:
df["Fully"] = df["Fully"].str.replace("/","")

In [23]:
df["Product Description"] = df["Product Description"].str.replace("?"," ")

In [24]:
df.columns = ["Car Name", "Price"]

In [25]:
df = df.iloc[2:]

In [26]:
df["Price"] = df["Price"].str.replace(",","")

In [27]:
df=df.reset_index(drop=True)

In [28]:
df["Price"] = pd.to_numeric(df["Price"])

In [29]:
df["Price"].dtype

dtype('int64')

In [30]:
df

                                 Car Name     Price
0                                 Alto VX   1113000
1                                Alto VXR   1335000
2                                Alto VXL   1521000
3                              WagonR VXR   1530000
4                              WagonR VXL   1610000
5                              WagonR AGS   1760000
6                              Cultus VXR   1655000
7                              Cultus VXL   1830000
8                  Cultus Auto Gear Shift   1975000
9                Swift DLX 1.3 Navigation   1972000
10     Swift DLX Automatic 1.3 Navigation   2148000
11                            Jimny GA MT   4490000
12                         Vitara GLX 1.6   6500000
13                             VX Euro II   1049000
14                      Cargo Van Euro II   1075000
15                           Ravi Euro II   1034000
16              Toyota Yaris ATIV CVT 1.3   2669000
17               Toyota Yaris ATIV MT 1.3   2519000
18            Toyota Yaris ATIV X CVT 1.5   2899000
19             Toyota Yaris ATIV X MT 1.5   2719000
20               Toyota Yaris GLI CVT 1.3   2589000
21                Toyota Yaris GLI MT 1.3   2409000
22               Corolla Altis Manual 1.6   3109000
23            Corolla Altis Automatic 1.6   3249000
24                 Corolla Altis CVTi 1.8   3579000
25  Corolla Altis Grande 1.8 (Beige Inter   3869000
26   Corolla Altis Grande CVTi 1.8 (Black   3889000
27                 Hilux 4x2 S/C Deckless   3569000
28                 Hilux 4x2 S/C Standard   3819000
29             Hilux 4x4 S/C Standard 2.8   5169000
30                            Hilux E 2.8   5859000
31                       Hilux REVO G 2.8   6429000
32             Hilux REVO G Automatic 2.8   6779000
33             Hilux REVO V Automatic 2.8   7379000
34                         Fortuner 2.7 G   7649000
35                      Fortuner 2.7 VVTi   8899000
36                   Fortuner 2.8 Sigma 4   9269000
37                     Civic 1.5 Rs Turbo   4564000
38                    Civic 1.8 iVTEC CVT   3614000
39              Civic Oriel 1.8 iVTEC CVT   3864000
40                 Accord 1.5L VTEC Turbo  11999000
41                            BRV iVTEC S   3374000
42                            CRV 2.0 CVT  10700000